[package]
name = "swanson"
version = "0.1.0"
authors = ["Swellaby <opensource@swellaby.com>"]
description = "git commit messages, the Swanson way"
license = "MIT"
repository = "https://github.com/swellaby/swanson"
readme = "README.md"
edition = "2018"

[dependencies]
